### ISSUE TITLE
Correct build file path for virtual dependencies

### ISSUE THREAD

**Issue by Vampire** [dependency-check/dependency-check-gradle#172] opened 2020-01-17 17:46 UTC
Virtual dependencies are created with path `new File(project.buildDir.getParentFile(), "build.gradle")` which is not necessarily correct.
It would be better to simply use `project.buildFile`, which is the actual build file.
And even if not, it would be better to use `project.projectDir` instead of `project.buildDir.parentFile`.

**Comment by jeremylong** [comment] 2020-01-17 23:42
This is a duplicate of your previous issue #169.  I agree with you - we accept PRs, we just have not had the time to implement this yet. I expect this to be in the next release.

**Comment by Vampire** [comment] 2020-01-18 00:00
No, this is not a duplicate.
This is a totally different piece of code.
And a totally different issue.
Here you construct a file relative to an absolute file object which basically is ok, but produces the wrong result here, because
- the build file neither needs to be located in the parent directory of the build directory,
- nor does the project directory need to be located in the parent directory of the build directory,
- nor does the build file need to be named `build.gradle` or `build.gradle.kts`, but can be freely named and located in the `settings.gradle` file.

#169 is about `new File(config.outputDirectory)` which can go greatly wrong if `config.outputDirectory`  - which is a `String` coming from user code - is set to a relative path as it is then dependent on the working directory.

**Comment by jeremylong** [comment] 2022-03-04 11:28
sorry this took so long to get back to for such a simple fix.

**Closed** 2022-03-04 11:28 UTC
