### ISSUE TITLE
Compatibility with gradle 7

### ISSUE THREAD

**Issue by occhioni-esteco** [dependency-check/dependency-check-gradle#229] opened 2021-09-30 06:26 UTC
Hi, seems that the plugin is not Gradle 7 compliant. 

When running task (dependencyCheck or dependencyCheckAggregate) from dependency-check plugin with the option `--warning-mode all` what i get is the following error list: 

> The archives configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath or runtimeClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
> The default configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath or runtimeClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
> The compile configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
> The compileOnly configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
> The runtime configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the runtimeClasspath configuration instead. Consult the upgrading guide for further information: 
> https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

**Comment by jeremylong** [comment] 2021-09-30 12:27
The plugin is compatible - ODC is just pulling in the scopes within the build. When you use gradle 7+ the scopes it is complaining about won't be present so ODC will not attempt to pull them in.

**Comment by Simulant87** [comment] 2022-03-09 15:00
I can confirm that with gradle 7.4 it still works for me.

**Comment by cstsw** [comment] 2023-06-21 11:03
I'd like to suggest to close this issue. As Jeremy explained the warnings produced by Gradle 6 can be ignored. And I can confirm that the ODC Gradle Plugin runs without any complications on all of the most recent Gradle major versions (6.9.4, 7.6.1, 8.1.1).

**Closed** 2023-06-21 11:18 UTC
Labels: question
