### ISSUE TITLE
Gradle 7 Deprecation Warnings When Running dependencyCheckAggregate on Gradle 6.5.1

### ISSUE THREAD

**Issue by ericparton** [dependency-check/dependency-check-gradle#194] opened 2020-07-27 19:30 UTC
I'm using the plugin on large Gradle project with the latest version of Gradle (6.5.1). When we run the dependencyCheckAggregate task, we see these deprecation warnings everywhere in the logs:

`The configuration :my_project:compileClasspath was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a different project. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5.1/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors for more details.
`

Based on these warnings, it appears that the plugin will not work on future versions of Gradle and needs to be refactored in some way.

**Comment by karuppiah7890** [comment] 2020-08-17 10:07
This happens with `dependencyCheckAnalyze` task too!

**Comment by karuppiah7890** [comment] 2020-08-17 10:11
@ericparton I think we can close this as duplicate of #176

**Comment by jeremylong** [comment] 2021-05-23 12:23
Please see https://github.com/jeremylong/DependencyCheck/issues/2644#issuecomment-706114730

**Closed by jeremylong** 2021-05-23 12:23 UTC
