### ISSUE TITLE
Could not find method sha256Checksum() when upgrade to version 7.0.0

### ISSUE THREAD

**Issue by anasoid** [dependency-check/dependency-check-gradle#253] opened 2022-03-07 07:03 UTC
I have the following error when upgrade from 6.5.3 to 7.0.0 using gradle 7.4.

 Execution failed for task ':dependencyCheckAggregate'.
> Could not find method sha256Checksum() for arguments [org.anasoid.jmc:jmc-core:unspecified] on task ':dependencyCheckAggregate' of type org.owasp.dependencycheck.gradle.tasks.Aggregate.

You can see more detail on https://github.com/anasoid/jmeter-as-code/pull/202

**Comment by jeremylong** [comment] 2022-03-07 11:35
duplicate of #251 - will be fixed in 7.0.1 which should be released this week.

**Closed by jeremylong** 2022-03-07 11:35 UTC
Labels: duplicate
